# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import resources

class InformationIcon(QtWidgets.QWidget):
    def __init__(self, parent = None):
        super(InformationIcon, self).__init__(parent)

    def paintEvent(self, event) -> None:
        pixmap = QtGui.QPixmap()
        pixmap.load(":/icons/icon.png")
        paint = QtGui.QPainter(self)
        width = self.width()
        height = self.height()
        pixmap = pixmap.scaled(width, height, QtCore.Qt.AspectRatioMode.KeepAspectRatioByExpanding)
        paint.drawPixmap(0, 0, pixmap)

        return super().paintEvent(event)

class Information(QtWidgets.QWidget):
    def __init__(self, parent = None):
        super(Information, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Information")
        self.resize(270, 70)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.icon = InformationIcon(parent=self)
        self.icon.setMinimumSize(QtCore.QSize(32, 32))
        self.icon.setMaximumSize(QtCore.QSize(32, 32))
        self.icon.setObjectName("icon")
        self.verticalLayout_3.addWidget(self.icon)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.text = QtWidgets.QLabel(parent=self)
        self.text.setObjectName("text")
        self.verticalLayout_4.addWidget(self.text)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Information", "Information"))
        self.text.setText(_translate("Information", "\nВерсия 0.0.1"))
