# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import re
from PyQt6 import QtCore, QtGui, QtWidgets

class Settings(QtWidgets.QMainWindow):
    def __init__(self, parent = None):
        super().__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Settings")
        self.resize(605, 650)
        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.folderPath = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.folderPath.setMinimumSize(QtCore.QSize(0, 0))
        self.folderPath.setObjectName("folderPath")
        self.horizontalLayout_2.addWidget(self.folderPath)
        self.openButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout_2.addWidget(self.openButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.filenamePattern = QtWidgets.QLineEdit(parent=self.groupBox)
        self.filenamePattern.setObjectName("filenamePattern")
        self.horizontalLayout_14.addWidget(self.filenamePattern)
        self.checkButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.checkButton.setObjectName("checkButton")
        self.horizontalLayout_14.addWidget(self.checkButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.verticalLayout_6.addLayout(self.verticalLayout_10)
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setEnabled(True)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.label_9.setVisible(False)
        sizePolicy = QtWidgets.QSizePolicy()
        sizePolicy.setRetainSizeWhenHidden(True)
        self.label_9.setSizePolicy(sizePolicy)
        self.verticalLayout_6.addWidget(self.label_9)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 22))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.timeColumn = QtWidgets.QSpinBox(parent=self.groupBox_2)
        self.timeColumn.setEnabled(False)
        self.timeColumn.setMinimumSize(QtCore.QSize(50, 0))
        self.timeColumn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.timeColumn.setObjectName("timeColumn")
        self.horizontalLayout_3.addWidget(self.timeColumn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.valuesColumn = QtWidgets.QSpinBox(parent=self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valuesColumn.sizePolicy().hasHeightForWidth())
        self.valuesColumn.setSizePolicy(sizePolicy)
        self.valuesColumn.setMinimumSize(QtCore.QSize(50, 0))
        self.valuesColumn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.valuesColumn.setMinimum(1)
        self.valuesColumn.setObjectName("valuesColumn")
        self.horizontalLayout_5.addWidget(self.valuesColumn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.start = QtWidgets.QDoubleSpinBox(parent=self.groupBox_2)
        self.start.setMinimumSize(QtCore.QSize(100, 0))
        self.start.setMaximumSize(QtCore.QSize(100, 16777215))
        self.start.setMaximum(100.0)
        self.start.setObjectName("start")
        self.horizontalLayout_7.addWidget(self.start)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.end = QtWidgets.QDoubleSpinBox(parent=self.groupBox_2)
        self.end.setMinimumSize(QtCore.QSize(100, 0))
        self.end.setMaximumSize(QtCore.QSize(100, 16777215))
        self.end.setMaximum(100.0)
        self.end.setObjectName("end")
        self.horizontalLayout_8.addWidget(self.end)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelsCheckbox = QtWidgets.QCheckBox(parent=self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelsCheckbox.sizePolicy().hasHeightForWidth())
        self.labelsCheckbox.setSizePolicy(sizePolicy)
        self.labelsCheckbox.setObjectName("labelsCheckbox")
        self.horizontalLayout_11.addWidget(self.labelsCheckbox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_6.setMinimumSize(QtCore.QSize(180, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.horizontalLabel = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.horizontalLabel.setEnabled(False)
        self.horizontalLabel.setObjectName("horizontalLabel")
        self.horizontalLayout_9.addWidget(self.horizontalLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(180, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.verticalLabel = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.verticalLabel.setEnabled(False)
        self.verticalLabel.setObjectName("verticalLabel")
        self.horizontalLayout_10.addWidget(self.verticalLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_13.addWidget(self.saveButton)
        self.status = QtWidgets.QWidget(parent=self.centralwidget)
        self.status.setMinimumSize(QtCore.QSize(22, 22))
        self.status.setMaximumSize(QtCore.QSize(22, 22))
        self.status.setStyleSheet("background-color: rgba(0, 0, 0, 255);")
        self.status.setObjectName("status")
        self.horizontalLayout_13.addWidget(self.status)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_6.addWidget(self.progressBar)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_6)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_12.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()

        self.openButton.clicked.connect(self.openFolder)
        self.checkButton.clicked.connect(self.checkParams)
        self.labelsCheckbox.stateChanged.connect(self.enableLabels)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Settings", "Settings"))
        self.label_4.setText(_translate("Settings", "Открыть папку"))
        self.openButton.setText(_translate("Settings", "Обзор"))
        self.groupBox.setTitle(_translate("Settings", "Шаблон имен файлов"))
        self.checkButton.setText(_translate("Settings", "Проверить"))
        self.label_9.setText(_translate("Settings", "Найдено"))
        self.groupBox_2.setTitle(_translate("Settings", "Задание столбцов и граничные значения"))
        self.label.setText(_translate("Settings", "Номер столца со временем"))
        self.label_5.setText(_translate("Settings", "Номер столца со значениями"))
        self.label_2.setText(_translate("Settings", "Начало временного интервала"))
        self.label_3.setText(_translate("Settings", "Конец временного интервала"))
        self.groupBox_3.setTitle(_translate("Settings", "Отображение на графике"))
        self.labelsCheckbox.setText(_translate("Settings", "Включить отображение меток на осях"))
        self.label_6.setText(_translate("Settings", "Метка на горизонтальной оси"))
        self.label_7.setText(_translate("Settings", "Метка на вертикальной оси"))
        self.saveButton.setText(_translate("Settings", "Сохранить"))
        self.progressBar.setFormat(_translate("Settings", "%p%"))
        self.pushButton_2.setText(_translate("Settings", "Вычислить"))

    def openFolder(self):
        path = QtWidgets.QFileDialog.getExistingDirectory(self, "Выберите папку")

        if os.path.exists(path):
            self.folderPath.setText(path)

    def checkParams(self):
        path = self.folderPath.text()
        pattern = self.filenamePattern.text()

        param = "\{[^\}]*\}"
        
        def get_dec_point(s):
            return s[-1] if len(s) > 1 else ""

        def get_equal(s):
            return s[-2] if len(s) > 2 else ""

        def strip(s):
            return s[1:-1] if len(s) > 2 else ""

        matches = re.findall(param, pattern)
        pattern_with_repl = pattern[:]

        for match in matches:
            striped_match = strip(match)

            equal = get_equal(striped_match)
            dec_point = get_dec_point(striped_match)

            has_equal = False
            has_dec_point = False

            if len(equal) > 0:
                has_equal = True
            
            if len(dec_point) > 0:
                has_dec_point = True

            offset = (1 if has_equal else 0) + (1 if has_dec_point else 0)
            symbol = striped_match[:-offset] if offset > 0 else striped_match
            replacement = f"({symbol}{equal}[+-]?(?:[0-9]*[{dec_point}])?[0-9]+)"
            pattern_with_repl = pattern_with_repl.replace(match, replacement)
            
        print(pattern_with_repl)

        if os.path.exists(path):
            files = os.listdir(path)

            count = 0

            for file in files:
                if os.path.isfile(os.path.join(path, file)):
                    matches = re.findall(pattern_with_repl, file)
                    print(matches)

                    if len(matches) == 1 and len(matches[0]) == 2:
                        count += 1
            
            self.label_9.setText(f"Найдено: {count}")
            self.label_9.setVisible(True)


    def enableLabels(self):
        self.horizontalLabel.setEnabled(not self.horizontalLabel.isEnabled())
        self.verticalLabel.setEnabled(not self.verticalLabel.isEnabled())